package com.elibrary.entity;

public enum ActionStatus {

	LATEST, POPULAR, RECOMMEND, UNFAVOURITE, UNBOOKMARK, FAVOURITE, READ, BOOKMARK, RATING, DOWNLOAD, UPLOAD, EDIT, DELETED, CREATELIBRARIAN, CREATEUSER, CREATESUPERVISOR;

}
